cmake_minimum_required(VERSION 3.15)

project(demo1)

add_subdirectory(res)

aux_source_directory(. SOURCES)
aux_source_directory(ui SOURCES)
aux_source_directory(ui/data SOURCES)
aux_source_directory(ui/page_ai SOURCES)
aux_source_directory(ui/utils SOURCES)
aux_source_directory(ui/utils/clock SOURCES)
aux_source_directory(ui/utils/file SOURCES)

add_executable(demo1 ${SOURCES})

target_include_directories(demo1 PRIVATE
                        ./
                        ui/
                        ui/data/
                        ui/page_ai/
                        ui/utils/
                        ui/utils/clock/
                        ui/utils/file/
                        res/
                        res/color/
                        res/font/
                        res/music/
                        res/image/
                        ${CMAKE_SOURCE_DIR}/lvgl
                        ${CMAKE_SOURCE_DIR}/lvgl/src
                        ${CMAKE_SOURCE_DIR}/lvgl/demos
                        ${CMAKE_SOURCE_DIR}/component/hal
                        ${CMAKE_SOURCE_DIR}/component/wifi
                        ${CMAKE_SOURCE_DIR}/component/net
                        ${CMAKE_SOURCE_DIR}/component/osal
                        ${CMAKE_SOURCE_DIR}/component/font
                        ${CMAKE_SOURCE_DIR}/component/player
                        ${CMAKE_SOURCE_DIR}/component/usb_hid
                        ${CMAKE_SOURCE_DIR}/component/net/inc
                        ${CMAKE_SOURCE_DIR}/component/bt_audio
)

target_link_libraries(demo1 PRIVATE
                        lvgl_demos
                        lvgl
                        lvgl_porting
                        wifi
                        http
                        player
                        font
                        usb_hid
                        bt_audio
                        )


if(SIMULATOR_LINUX)
    add_compile_definitions(SIMULATOR_LINUX)
    set(PROJECT_RES_URL ${PROJECT_BINARY_DIR}/res/)
else()
    set(PROJECT_RES_URL /usr/res/)
endif()
target_compile_definitions(demo1 PUBLIC PROJECT_RES_URL="${PROJECT_RES_URL}")
message("PROJECT_RES_URL is ${PROJECT_RES_URL}")


